[[language]]
name = "yaml"
file-types = ["yaml", "yml"]
language-servers = [ "yaml-language-server" ]
formatter = { command = "bat", args = ["-l", "yaml"] }

[language-server.yaml-language-server]
config = { yaml = { schemas = { kubernetes = "/*.y{a,}ml" }, format = { enable = true } } }

